# Generated by Django 2.1.7 on 2019-04-23 10:33

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import tagging.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Maximum 250 characters.', max_length=250)),
                ('slug', models.SlugField(help_text='Suggested value automatically generated from title. Must be unique', unique=True)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Maximum 250 characters.', max_length=250)),
                ('slug', models.SlugField(help_text='Suggested value automatically generated from title. Must be unique.', unique_for_date='pub_date')),
                ('excerpt', models.TextField(blank=True, help_text='A short summary of the entry. Optional.')),
                ('body', models.TextField()),
                ('cover_pic', models.FileField(blank=True, help_text='Cover image for entry. Optional.', null=True, upload_to='Uploads/entries')),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now)),
                ('enable_comments', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False)),
                ('status', models.IntegerField(choices=[(1, 'Live'), (2, 'Draft')], default=1, help_text='Only entries with live status will be publicly displayed.')),
                ('excerpt_html', models.TextField(blank=True, editable=False)),
                ('body_html', models.TextField(blank=True, editable=False)),
                ('tags', tagging.fields.TagField(blank=True, help_text='Separate tags with spaces.', max_length=255)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('categories', models.ManyToManyField(to='weblog.Category')),
            ],
            options={
                'verbose_name_plural': 'Entries',
                'ordering': ['title'],
            },
            managers=[
                ('live', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('description_html', models.TextField(blank=True)),
                ('url', models.URLField(unique=True, verbose_name='URL')),
                ('via_name', models.CharField(blank=True, help_text='The name of the person whose site you spotted the link on. Optional.', max_length=250, verbose_name='Via')),
                ('via_url', models.URLField(blank=True, help_text='The URL of the site where you spotted the link. Optional.', verbose_name='Via URL')),
                ('enable_comments', models.BooleanField(default=True)),
                ('post_elsewWhere', models.BooleanField(default=True, help_text='If checked, this link will be posted both to your weblog and to your del.icio.us account.', verbose_name='Post to del.icio.us')),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now)),
                ('slug', models.SlugField(help_text='Must be unique for the publication date.', unique_for_date='pub_date')),
                ('tags', tagging.fields.TagField(blank=True, max_length=255)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            managers=[
                ('object_fetcher', django.db.models.manager.Manager()),
            ],
        ),
    ]
