# Generated by Django 2.1.7 on 2019-04-23 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0002_auto_20190423_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='featured',
            field=models.BooleanField(default=True),
        ),
    ]
