# Generated by Django 2.1.7 on 2019-04-26 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0003_auto_20190423_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='post_elsewWhere',
            field=models.BooleanField(default=True, help_text='If checked, this link will be posted both to your weblog.', verbose_name='Post to admagovgh.herokuapp.com'),
        ),
    ]
