# Generated by Django 2.1.7 on 2019-04-27 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0004_auto_20190426_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='description',
            field=models.TextField(blank=True, help_text='A brief description of the URL/Link. Optional.'),
        ),
        migrations.AlterField(
            model_name='link',
            name='description_html',
            field=models.TextField(blank=True, help_text='A brief description of the URL/Link. Optional.'),
        ),
    ]
