# Generated by Django 2.1.7 on 2019-04-29 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0005_auto_20190427_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='excerpt_html',
            field=models.TextField(blank=True, editable=False, max_length=20),
        ),
    ]
