# Generated by Django 2.1.7 on 2019-05-02 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0007_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
