# Generated by Django 2.1.7 on 2019-05-02 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0008_delete_contact'),
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchkeyword',
            name='link',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='weblog.Link'),
            preserve_default=False,
        ),
    ]
