# Generated by Django 2.1.7 on 2019-05-02 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_searchkeyword_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchkeyword',
            name='link',
        ),
    ]
